### ISSUE TITLE
关于 GitHub Pages 的设置细节

### ISSUE THREAD

**Issue by log-Z** [log-Z/nav#29]
@artisanbox 朋友，注意到你遇到一些困难。请在仓库设置中将 GitHub Pages 来源设置为 GitHub Actions ，否则部署过去的只是源码而已。按理来说，默认值就应该是这个。
调整好设置之后[手动运行](https://github.com/log-Z/nav#手动运行工作流)一下 `Deploy to GitHub Pages` 工作流，让它重新部署一下即可。
![image](https://github.com/log-Z/nav/assets/25786567/cf5d9c74-ea0e-48e0-8a94-168f04afcbc2)

**Comment by artisanbox** [comment]
hi，你好，我之前已经做好了部署了，玩了一下项目很不错。因为某些原因，后面下线部署了。感谢作者。

**Comment by log-Z** [comment]
@artisanbox 哈不用谢，随意玩吧~
